name: WPS Daily Sign-In

on:
  schedule:
    - cron: '15 0 * * *' 
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: 检查log判断是否存在“原因”二字，若存在则代表cookie可能失效
        id: check_log
        run: |
          if [ -f "log/wps.txt" ] && grep -q "原因" "log/wps.txt"; then
            echo "检测到之前的签到日志包含'原因'，停止运行"
            echo "has_failure=true" >> $GITHUB_OUTPUT
          else
            echo "has_failure=false" >> $GITHUB_OUTPUT
          fi
      
      - name: cookie 失效，停止运行
        if: steps.check_log.outputs.has_failure == 'true'
        run: |
          echo "由于上次签到失败，工作流已停止"
          exit 1
      
      - name: 配置python环境
        if: steps.check_log.outputs.has_failure == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        if: steps.check_log.outputs.has_failure == 'false'
        run: |
          pip install requests pycryptodome
      
      - name: 运行签到脚本
        if: steps.check_log.outputs.has_failure == 'false'
        env:
          WPS_USER_ID: ${{ secrets.WPS_USER_ID }}
          WPS_SID: ${{ secrets.WPS_SID }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          
        run: |
          python wps.py
      
      - name: 写入日志
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: signin-log
          path: log/wps.txt
      
      - name: 推送
        if: always()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add log/wps.txt
          git diff --staged --quiet || git commit -m "Update WPS sign-in log [skip ci]"
          git push
